# AUTO-GENERATED BY INSTALLER
PROJECT_TITLE = 'IOT Application For Tracking Farm Animals And Utilizing Their Biological Data'
CUSTOM_ALGOS = []
COPYRIGHT_TEXT = "© Copyright: Dr Subar - FIST MMU Melaka Dec 2025"
